name: Create Release and Packages

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build-python-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: python-package
          path: dist/

  build-arch-package:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build package
        run: |
          pacman -Syu --noconfirm base-devel
          cd packaging/arch
          makepkg -sf
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: arch-package
          path: packaging/arch/*.pkg.tar.zst

  build-debian-package:
    runs-on: ubuntu-latest
    container: debian:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build package
        run: |
          apt-get update
          apt-get install -y build-essential debhelper devscripts
          cd packaging/debian
          debuild -us -uc
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: debian-package
          path: ../*.deb

  build-fedora-package:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build package
        run: |
          dnf install -y rpm-build
          cd packaging/fedora
          rpmbuild -ba hiveden.spec
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: fedora-package
          path: /root/rpmbuild/RPMS/noarch/*.rpm

  upload-assets:
    runs-on: ubuntu-latest
    needs: [create-release, build-python-package, build-arch-package, build-debian-package, build-fedora-package]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Upload Python sdist
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: artifacts/python-package/*.tar.gz
          asset_name: hiveden-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
      - name: Upload Python wheel
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: artifacts/python-package/*.whl
          asset_name: hiveden-${{ github.ref_name }}-py3-none-any.whl
          asset_content_type: application/zip
      - name: Upload Arch package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: artifacts/arch-package/*.pkg.tar.zst
          asset_name: hiveden-${{ github.ref_name }}.pkg.tar.zst
          asset_content_type: application/octet-stream
      - name: Upload Debian package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: artifacts/debian-package/*.deb
          asset_name: hiveden-${{ github.ref_name }}.deb
          asset_content_type: application/vnd.debian.binary-package
      - name: Upload Fedora package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: artifacts/fedora-package/*.rpm
          asset_name: hiveden-${{ github.ref_name }}.rpm
          asset_content_type: application/x-rpm
